/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (3.3.4-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.toblerones.parking.meters.controllers;

import com.toblerones.parking.meters.model.Location;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2018-11-25T22:07:29.638+11:00[Australia/Sydney]")

@Validated
@Api(value = "parkingInfo", description = "the parkingInfo API")
public interface ParkingInfoApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    @ApiOperation(value = "", nickname = "parkingInfoPost", notes = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "true") })
    @RequestMapping(value = "/parkingInfo",
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<Void> parkingInfoPost(@ApiParam(value = "parking information request", required = true) @Valid @RequestBody Location location) {
        return new ResponseEntity<>(HttpStatus.OK);

    }

}
